apiVersion: controllers.trishanku.org.trishanku.org/v1alpha1
kind: AutomatedMerge
metadata:
  labels:
    app.kubernetes.io/name: automatedmerge
    app.kubernetes.io/instance: sample-k8s-kcm
    app.kubernetes.io/part-of: trishanku-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: trishanku-controller
  name: sample-k8s-kcm
spec:
  gitcd:
    credentialsSecretName: git-cred
    imagePullSecretName: gar-cred
    gitcdImage:
      imagePullPolicy: Always
    git:
      branches:
        data: upstream/data
        metadata: upstream/metadata
      remotes:
      - name: kcm
        repo: https://github.com/trishanku-org/sample-k8s
        branches:
          data: kcm/data
          metadata: kcm/metadata
          failOnNoBranch: true
      - name: mcm
        repo: https://github.com/trishanku-org/sample-k8s
        branches:
          data: mcm/data
          metadata: mcm/metadata
          failOnNoBranch: true
    pull:
      pushAfterMerge: true
      pushOnPullFailure: true
      tickerDuration: 15s
  app:
    replicas: 1
    entrypointsConfigMapName: sample-k8s-entrypoints
    committerName: automerge