# ! d2 --sketch apiserver-binary-compatibility.d2 ../png/apiserver-binary-compatibility.png
direction: right
classes: {
  container: {
    label: ""
  }
  controller: {
    icon: ../svg/Kubernetes_logo_without_workmark.svg
  }
  apiserver: {
    icon: ../svg/api.svg
  }
  shim: {
    icon: ../png/etcd-glyph-color.png
  }
  git: {
    shape: cylinder
    icon: ../png/Git-Icon-1788C.png
  }
}

p1: {
  class: container

  c: Controller 1 {class: controller}
  kube-apiserver: {class: apiserver}
  etcd shim: {class: shim}
  git: {class: git}

  c <-> kube-apiserver <-> etcd shim <-> git
}

p2: {
  class: container

  git: {class: git}
  etcd shim: {class: shim}
  kube-apiserver: {class: apiserver}
  c: Controller 2 {class: controller}

  git <-> etcd shim <-> kube-apiserver <-> c
}

p1.git -> p2.git
p2.git -> p1.git
