# ! d2 --sketch controllers.d2 ../png/controllers.png
direction: right

classes: {
  controller: {
    icon: ../png/logo.png
  }
}

kube-apiserver: {
  icon: ../png/api-128.png
}

etcd: {
  shape: cylinder
  icon: ../png/etcd-glyph-color.png
}

Controller 1: {
  class: controller

  cache: {shape: cylinder}
}
Controller 2: {
  class: controller

  cache: {shape: cylinder}
}

Controller 1 <-> kube-apiserver
Controller 2 <-> kube-apiserver
kube-apiserver <-> etcd

note: |md
  - Normalies the divergence between the desired and the actual state
  - Controllers need access to the central consensus to act
  - Cache could be stale but never dirty
| {near: bottom-center}
