# ! d2 --sketch controllers-git.d2 ../png/controllers-git.png
direction: right
classes: {
  container: {
    label: ""
  }
  controller: {
    icon: ../png/logo.png
  }
  git: {
    shape: image
    icon: ../png/Git-Icon-1788C.png
  }
}

c1: Controller 1 {
  class: controller

  git: {class: git}
}

c2: Controller 2 {
  class: controller

  git: {class: git}
}

c1.git -> c2.git
c2.git -> c1.git
