# ! d2 --sketch controllers-with-gitcd-simplified.d2 ../png/controllers-with-gitcd-simplified.png
direction: right
classes: {
  container: {
    label: ""
  }
  controller: {
    icon: ../png/logo.png
  }
  apiserver: {
    icon: ../png/api-128.png
  }
  gitcd: {
    icon: ../png/etcd-glyph-color.png
  }
  storage: {
    shape: cylinder
    label: ""
  }
  etcd: {
    shape: image
    icon: ../png/etcd-glyph-color.png
  }
  git: {
    shape: image
    icon: ../png/Git-Icon-1788C.png
  }
}

p1: {
  class: container

  c: Controller 1 {class: controller}
  kube-apiserver: {class: apiserver}
  gitcd: {class: gitcd}
  storage: {
    class: storage

    git: {class: git}
  }

  c <-> kube-apiserver <-> gitcd <-> storage.git
}

p2: {
  class: container

  storage: {
    class: storage

    git: {class: git}
  }
  gitcd: {class: gitcd}
  kube-apiserver: {class: apiserver}
  c: Controller 2 {class: controller}

  storage.git <-> gitcd <-> kube-apiserver <-> c
}

p1.gitcd <- p2.storage.git: pull
p2.gitcd <- p1.storage.git: pull
