# ! d2 --sketch controllers.d2 ../png/controllers.png
direction: right

classes: {
  controller: {
    icon: ../svg/Kubernetes_logo_without_workmark.svg
  }
}

kube-apiserver: {
  icon: ../svg/api.svg
}

etcd: {
  shape: cylinder
  icon: ../png/etcd-glyph-color.png
}

Controller 1: {class: controller}
Controller 2: {class: controller}

Controller 1 <-> kube-apiserver
Controller 2 <-> kube-apiserver
kube-apiserver <-> etcd
