#! d2 --sketch headless-sequence.d2 ../png/headless-sequence.png

shape: sequence_diagram

setup: Setup {
    shape: person
    style: {fill: lightgray}
}

host: Host Cluster {
    icon: ../png/logo.png
}

setup.prepare -> host.prepare: Apply GitHubRepository Controller

ghc: GitHubRespository Controller {
   icon: ../png/github-mark.png
}

host.prepare -> ghc: Reconcile

setup.prepare -> host.prepare: Apply TrishankuHeaven Controller

tc: TrishankuHeaven Controller {
   icon: ../png/logo.png
}

host.prepare -> tc: Reconcile

setup.prepare -> host.prepare: Apply AutomatedMerge Controller

amc: AutomatedMerge Controller {
   icon: ../png/logo.png
}

host.prepare -> amc: Reconcile

setup.gh -> host.gh: Apply Upstream GitHubRepository

upstream: Upstream GitHubRepository {
    icon: ../png/github-mark.png
    style: {fill: lightgreen}
}

ghc.gh -> upstream.gh: Reconcile

setup.c1 -> host.c1: Apply kube-controller-manager TrishankuHeaven

tc.c1 -> host.c1: Reconcile kube-controller-manager secrets, configmaps and Deployment

kcm: kube-controller-manager {
    icon: ../png/c-m-128.png
    style: {fill: lightgreen}
}

host.c1 -> kcm.c1: Reconcile

upstream.gh.c1 -> kcm.c1.c1: Pull main branch {
    style: {animated: true}
}

kcm.c1.c1 -> upstream.gh.c1: Merge and push kcm branch {
    style: {animated: true}
}

setup.c2 -> host.c2: Apply kube-scheduler TrishankuHeaven

tc.c2 -> host.c2: Reconcile kube-scheduler secrets, configmaps and Deployment

scheduler: kube-scheduler {
    icon: ../png/sched-128.png
    style: {fill: lightgreen}
}

host.c2 -> scheduler.c2: Reconcile

upstream.gh.c2 -> scheduler.c2.c1: Pull main branch {
    style: {animated: true}
}

scheduler.c2.c1 -> upstream.gh.c2: Merge and push scheduler branch {
    style: {animated: true}
}

setup.c3 -> host.c3: Apply AutomatedMerge

amc.c1 -> host.c3: Reconcile automated-merge configmaps and Deployment

am: automated-merge {
    icon: ../png/logo.png
    style: {fill: lightgreen}
}

host.c3 -> am.c1: Reconcile

upstream.gh.c3 -> am.c1.c1: Pull kcm, scheduler and kubelet branches {
    style: {animated: true}
}

am.c1.c1 -> upstream.gh.c3: Merge and push main branch {
    style: {animated: true}
}

setup.c4 -> setup.c4:  Provision a Virtual Machine

node: Virtual Machine / Headless Node {
    icon: ../png/node-128.png
    style: {fill: lightgreen}
}

setup.c4 -> node.c1: Deploy kubelet in a trishanku heaven pointing to the Upstream Git Repository

upstream.gh.c4 -> node.c1.kubelet: Pull main branch {
    style: {animated: true}
}

node.c1.kubelet -> upstream.gh.c4: Merge and push kubelet branch {
    style: {animated: true}
}
