# ! d2 --sketch headless-kubernetes.d2 ../png/headless-kubernetes.png
direction: down

classes: {
  kubernetes: {
    icon: ../png/logo.png
  }
  apiserver: {
    style: {fill: transparent}
    icon: ../png/api-128.png
  }
  deploy: {
    style: {fill: transparent}
    icon: ../png/deploy-128.png
  }
  node: {
    icon: ../png/node-128.png
  }
  kubelet: {
    icon: ../png/kubelet-128.png
    style: {fill: transparent}
  }
  pod: {
    icon: ../png/pod-128.png
    style: {fill: transparent}
  }
  crd: {
    icon: ../png/crd-128.png
    style: {fill: transparent}
  }
  kcm: {
    icon: ../png/c-m-128.png
    style: {fill: transparent}
  }
  scheduler: {
    icon: ../png/sched-128.png
    style: {fill: transparent}
  }
  etcd: {
    icon: ../png/etcd-glyph-color.png
    style: {fill: transparent}
  }
  git: {
    icon: ../png/Git-Icon-1788C.png
  }
  invisible: {
    style: {
      opacity: 0.0
    }
  }
  package: {
    shape: package
    style: {fill: transparent}
  }
  branch: {
    shape: stored_data
    icon: ../png/9026745_git_branch_thin_icon.png
    style: {fill: transparent}
  }
}

Home: {
  shape: circle
  near: bottom-center
  link: steps.1
  style: {opacity: 0.0}
}

steps: {
  1: {
    back: back {
      shape: circle
      near: bottom-left
      link: 11.svg
      style: {opacity: 0.0}
    }
    next: Next {
      shape: circle
      near: bottom-right
      link: 2.svg
      style: {opacity: 0.0}
    }

    hc: Host Cluster {
      class: kubernetes

      api: kube-apiserver {class: apiserver}
      dc: Deployment Controller {class: deploy}
      dc -> api

      tc: TrishankuHeaven Controller {class: crd}
      tc -> api

      node: Node {
        class: node
        style: {fill: transparent}

        kubelet: {class: kubelet}
        kubelet -> _.api
      }
    }

    upstream: {
      shape: cylinder
      class: git

      mk: {
        class: invisible

        main: {
          class: package

          data: {class: branch}
          metadata: {class: branch}
        }

        kcm: {
          class: package

          data: {class: branch}
          metadata: {class: branch}
        }
      }

      sk: {
        class: invisible

        scheduler: {
          class: package

          data: {class: branch}
          metadata: {class: branch}
        }

        kubelet: {
          class: package

          data: {class: branch}
          metadata: {class: branch}
        }
      }
    }

    hc.tc.kcm: kube-controller-manager {
      class: crd
      style: {
        fill: orange
        opacity: 0.0
      }
    }

    hc.dc.kcm: kube-controller-manager {
      class: deploy
      style: {
        fill: orange
        opacity: 0.0
      }
    }

    hc.node.kcm: kube-controller-manager {
      class: pod
      style: {
        fill: orange
        opacity: 0.0
      }

      kcm: kube-controller-manager {
        class: kcm
        style: {opacity: 0.0}
      }
      api: kube-apiserver {
        class: apiserver
        style: {opacity: 0.0}
      }
      gitcd: {
        class: etcd
        style: {opacity: 0.0}

        git: {
          class: git
          shape: cylinder
          style: {
            opacity: 0.0
            fill: transparent
          }
        }
      }
    }

    hc.node.kcm.gitcd <- upstream.mk.main: fetch {
      style: {
        animated: true
        opacity: 0.0
      }
    }
    hc.node.kcm.gitcd -> upstream.mk.kcm: push {
      style: {
        animated: true
        opacity: 0.0
      }
    }
    hc.node.kcm.gitcd <- upstream.mk.kcm: fetch {
      style: {
        animated: true
        opacity: 0.0
      }
    }
    hc.node.kcm.gitcd -> upstream.mk.main: push {
      style: {
        animated: true
        opacity: 0.0
      }
    }

    hc.tc.scheduler: kube-scheduler {
      class: crd
      style: {
        fill: orange
        opacity: 0.0
      }
    }

    hc.dc.scheduler: kube-scheduler {
      class: deploy
      style: {
        fill: orange
        opacity: 0.0
      }
    }

    hc.node.scheduler: kube-scheduler {
      class: pod
      style: {
        fill: orange
        opacity: 0.0
      }

      scheduler: kube-scheduler {
        class: scheduler
        style: {opacity: 0.0}
      }
      api: kube-apiserver {
        class: apiserver
        style: {opacity: 0.0}
      }
      gitcd: {
        class: etcd
        style: {opacity: 0.0}

        git: {
          class: git
          shape: cylinder
          style: {
            opacity: 0.0
            fill: transparent
          }
        }
      }
    }

    hc.node.scheduler.gitcd <- upstream.mk.main: fetch {
      style: {
        animated: true
        opacity: 0.0
      }
    }
    hc.node.scheduler.gitcd -> upstream.sk.scheduler: push {
      style: {
        animated: true
        opacity: 0.0
      }
    }
    hc.node.scheduler.gitcd <- upstream.sk.scheduler: fetch {
      style: {
        animated: true
        opacity: 0.0
      }
    }
    hc.node.scheduler.gitcd -> upstream.mk.main: push {
      style: {
        animated: true
        opacity: 0.0
      }
    }

    headless: Headless Cluster {
      style: {opacity: 0.0}

      node: Virtual Machine {
        style: {
          fill: orange
          opacity: 0.0
        }

        kubelet: kubelet {
          class: kubelet
          style: {
            fill: orange
            opacity: 0.0
          }
        }
        api: kube-apiserver {
          class: apiserver
          style: {
            fill: orange
            opacity: 0.0
          }
        }
        gitcd: {
          class: etcd
          style: {
            fill: orange
            opacity: 0.0
          }

          git: {
            class: git
            shape: cylinder
            style: {
              opacity: 0.0
              fill: transparent
            }
          }
        }
      }
    }

    headless.node.gitcd <- upstream.mk.main: fetch {
      style: {
        animated: true
        opacity: 0.0
      }
    }
    headless.node.gitcd -> upstream.sk.kubelet: push {
      style: {
        animated: true
        opacity: 0.0
      }
    }
    headless.node.gitcd <- upstream.sk.kubelet: fetch {
      style: {
        animated: true
        opacity: 0.0
      }
    }
    headless.node.gitcd -> upstream.mk.main: push {
      style: {
        animated: true
        opacity: 0.0
      }
    }
  }
  2: {
    back.link: 1.svg
    next.link: 3.svg

    hc.tc.kcm.style.opacity: 1.0
  }
  3: {
    hc.tc.kcm.style.fill: transparent
    back.link: 2.svg
    next.link: 4.svg

    hc.dc.kcm.style.opacity: 1.0
  }
  4: {
    hc.dc.kcm.style.fill: transparent
    back.link: 3.svg
    next.link: 5.svg

    hc.node.kcm.style.opacity: 1.0
    hc.node.kcm.kcm.style.opacity: 1.0
    hc.node.kcm.api.style.opacity: 1.0
    hc.node.kcm.gitcd.style.opacity: 1.0
    hc.node.kcm.gitcd.git.style.opacity: 1.0

    (hc.node.kcm.gitcd <- upstream.mk.main)[0].style.opacity: 1.0
    (hc.node.kcm.gitcd -> upstream.mk.kcm)[0].style.opacity: 1.0
    (hc.node.kcm.gitcd <- upstream.mk.kcm)[0].style.opacity: 1.0
    (hc.node.kcm.gitcd -> upstream.mk.main)[0].style.opacity: 1.0

    upstream.mk.kcm.style.fill: orange
    upstream.mk.main.style.fill: orange
  }
  5: {
    hc.node.kcm.style.fill: transparent
    upstream.mk.kcm.style.fill: transparent
    upstream.mk.main.style.fill: transparent
    upstream.mk.kcm.style.fill: transparent
    back.link: 4.svg
    next.link: 6.svg

    hc.tc.scheduler.style.opacity: 1.0
  }
  6: {
    hc.tc.scheduler.style.fill: transparent
    back.link: 5.svg
    next.link: 7.svg

    hc.dc.scheduler.style.opacity: 1.0
  }
  7: {
    hc.dc.scheduler.style.fill: transparent
    back.link: 6.svg
    next.link: 8.svg

    hc.node.scheduler.style.opacity: 1.0
    hc.node.scheduler.scheduler.style.opacity: 1.0
    hc.node.scheduler.api.style.opacity: 1.0
    hc.node.scheduler.gitcd.style.opacity: 1.0
    hc.node.scheduler.gitcd.git.style.opacity: 1.0

    (hc.node.scheduler.gitcd <- upstream.mk.main)[0].style.opacity: 1.0
    (hc.node.scheduler.gitcd -> upstream.sk.scheduler)[0].style.opacity: 1.0
    (hc.node.scheduler.gitcd <- upstream.sk.scheduler)[0].style.opacity: 1.0
    (hc.node.scheduler.gitcd -> upstream.mk.main)[0].style.opacity: 1.0

    upstream.sk.scheduler.style.fill: orange
    upstream.mk.main.style.fill: orange
  }
  8: {
    hc.node.scheduler.style.fill: transparent
    upstream.sk.scheduler.style.fill: transparent
    upstream.mk.main.style.fill: transparent
    upstream.sk.scheduler.style.fill: transparent
    back.link: 7.svg
    next.link: 9.svg

    headless.style.opacity: 1.0
    headless.node.style.opacity: 1.0
  }
  9: {
    headless.node.style.fill: transparent
    back.link: 8.svg
    next.link: 10.svg

    headless.node.kubelet.style.opacity: 1.0
    headless.node.api.style.opacity: 1.0
    headless.node.gitcd.style.opacity: 1.0
    headless.node.gitcd.git.style.opacity: 1.0

    (headless.node.gitcd <- upstream.mk.main)[0].style.opacity: 1.0
    (headless.node.gitcd -> upstream.sk.kubelet)[0].style.opacity: 1.0
    (headless.node.gitcd -> upstream.mk.main)[0].style.opacity: 1.0
    (headless.node.gitcd <- upstream.sk.kubelet)[0].style.opacity: 1.0

    upstream.sk.kubelet.style.fill: orange
    upstream.mk.main.style.fill: orange
  }
  10: {
    headless.node.gitcd.style.fill: transparent
    headless.node.api.style.fill: transparent
    headless.node.kubelet.style.fill: transparent
    upstream.sk.kubelet.style.fill: transparent
    upstream.mk.main.style.fill: transparent
    back.link: 9.svg
    next.link: 11.svg

    headless.class: kubernetes
    headless.node.label: Headless Node
    headless.node.class: node
    headless.node.style.fill: orange
  }
  11: {
    back.link: 10.svg
    next.link: 1.svg

    headless.style.fill: "#D8FBD8"
    headless.node.style.fill: lightgreen
    headless.node.kubelet.style.fill: darkseagreen
    headless.node.api.style.fill: honeydew
    headless.node.gitcd.style.fill: honeydew
    hc.node.kcm.kcm.style.fill: darkseagreen
    hc.node.kcm.api.style.fill: honeydew
    hc.node.kcm.gitcd.style.fill: honeydew
    hc.node.scheduler.scheduler.style.fill: darkseagreen
    hc.node.scheduler.api.style.fill: honeydew
    hc.node.scheduler.gitcd.style.fill: honeydew
    upstream.mk.main.style.fill: darkseagreen
    upstream.mk.kcm.style.fill: darkseagreen
    upstream.sk.scheduler.style.fill: darkseagreen
    upstream.sk.kubelet.style.fill: darkseagreen
  }
}
