#! d2 --sketch operators.d2 ../png/operators.png
direction: right

Human Coordination {
    shape: text
    near: bottom-center
}

Operator 1 { shape : person }
Operator 2 { shape : person }

Operator 1 <-> Operator 2