#! d2 --sketch two-headless-sequence-scaleup-blue-green.d2 ../png/two-headless-sequence-scaleup-blue-green.png

shape: sequence_diagram

setup: Setup {
    shape: person
    style: {fill: lightgray}
}

host: Green Cluster {
    icon: ../png/logo.png
    style: {fill: palegreen}
}

ghc: Green GitHubRespository Controller {
    icon: ../png/logo.png
    style: {fill: palegreen}
}

tc: Green TrishankuHeaven Controller {
    icon: ../png/logo.png
    style: {fill: palegreen}
}

amc: Green AutomatedMerge Controller {
    icon: ../png/logo.png
    style: {fill: palegreen}
}

upstream: Blue Upstream GitHubRepository {
    icon: ../png/github-mark.png
    style: {fill: palegreen}
}

setup.c1 -> host.c1: Apply kube-controller-manager TrishankuHeaven

tc.c1 -> host.c1: Reconcile kube-controller-manager secrets, configmaps and Deployment

kcm: Blue kube-controller-manager {
    icon: ../png/c-m-128.png
    style: {fill: aqua}
}

host.c1 -> kcm.c1: Reconcile

upstream.gh.c1 -> kcm.c1.c1: Pull main branch {
    style: {animated: true}
}

kcm.c1.c1 -> upstream.gh.c1: Merge and push kcm branch {
    style: {animated: true}
}

setup.c2 -> host.c2: Apply kube-scheduler TrishankuHeaven

tc.c2 -> host.c2: Reconcile kube-scheduler secrets, configmaps and Deployment

scheduler: Blue kube-scheduler {
    icon: ../png/sched-128.png
    style: {fill: aqua}
}

host.c2 -> scheduler.c2: Reconcile

upstream.gh.c2 -> scheduler.c2.c1: Pull main branch {
    style: {animated: true}
}

scheduler.c2.c1 -> upstream.gh.c2: Merge and push scheduler branch {
    style: {animated: true}
}

setup.c3 -> host.c3: Apply AutomatedMerge

amc.c1 -> host.c3: Reconcile automated-merge configmaps and Deployment

am: Blue automated-merge {
    icon: ../png/logo.png
    style: {fill: aqua}
}

host.c3 -> am.c1: Reconcile

upstream.gh.c3 -> am.c1.c1: Pull kcm, scheduler and kubelet branches {
    style: {animated: true}
}

am.c1.c1 -> upstream.gh.c3: Merge and push main branch {
    style: {animated: true}
}