name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
    
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        flavor: latest=true
        images: asia-south1-docker.pkg.dev/trishanku/trishanku/heaven
        tags: type=sha

    - name: Login to GAR
      uses: docker/login-action@v2
      with:
        registry: asia-south1-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GAR_JSON_KEY }}
          
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
